name: Sync Upstream Repository

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v2

      - name: Add upstream remote
        run: git remote add upstream https://github.com/Nekohy/pieces-os.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main

      - name: Push changes to your repository
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git push origin main
